#!/usr/bin/env sh

TEST_DIR=$(dirname "$0")
WHACK_RUN="$TEST_DIR/../whack-run"

assert_equal() {
    if [ "$ACTUAL" = "$EXPECTED" ]; then
        echo .
    else
        echo Assertion failed
        echo Actual was: $ACTUAL
        echo Expected was: $EXPECTED
        echo
        FAILED=1
    fi
}

# Normal usage
ACTUAL=`"$WHACK_RUN" "$TEST_DIR" cat /usr/local/whack/hello`
EXPECTED="Hello there!"
assert_equal

# --fork
ACTUAL=`"$WHACK_RUN" "$TEST_DIR" --fork cat /usr/local/whack/hello`
EXPECTED="Hello there!"
assert_equal

# --fork return code
`"$WHACK_RUN" "$TEST_DIR" --fork sh -c 'exit 2'`
ACTUAL="$?"
EXPECTED=2
assert_equal

# --fork return code when child is killed
`"$WHACK_RUN" "$TEST_DIR" --fork sh -c 'kill $$'`
ACTUAL="$?"
EXPECTED=143
assert_equal

if [ -n "$FAILED" ]; then
    echo "Tests failed"
    exit 1
fi
